name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@master
      with:
        submodules: true
    - uses: actions/upload-artifact@master
      with:
        name: Source
        path: ${{ github.workspace }}
